### ISSUE TITLE
There is a problem with output format

### ISSUE THREAD

**Issue by driftli** [TimothyYe/ydict#22]
I have tried to query word 'hello' like 'ydict hello', but get output like this, seems there is a bug where output the query info.
![image](https://user-images.githubusercontent.com/44229257/72697627-78af6c00-3b7b-11ea-8bcb-9540d1ce0b4f.png)

**Comment by TimothyYe** [comment]
![demo](https://user-images.githubusercontent.com/860685/72697950-f9229c80-3b7c-11ea-8db3-c3b6ba20bd80.gif)

@driftli  I tried it on one Linux machine, it seems OK. 
I think this issue may be related to your terminal tool, what terminal software do you use?
I tried `ydict` with `iTerm2`, `Kitty`, it works well.

**Comment by driftli** [comment]
![test](https://user-images.githubusercontent.com/44229257/72704348-87098200-3b93-11ea-9e24-2871d27ee5a5.gif)
@TimothyYe I tried it on different Linux machines with `xshell`, both of them seems abnormal. However, when I tried it on physical machine directly, it works. Did you test `ydict` on `xshell`?

**Comment by TimothyYe** [comment]
@driftli  I don't have a windows machine, so I didn't test it on `xshell`.

**Comment by ycrao** [comment]
It seems `briandowns/spinner` bug.  You can just try with `-q` option without `Querying ...`  progress tips. Working fine for me in `Windows cmd/powershell` .

```bash
ydict -q hello
```

**Comment by TimothyYe** [comment]
I can disable the spinner for windows system.

**Comment by TimothyYe** [comment]
Disabled spinner on windows system https://github.com/TimothyYe/ydict/releases/tag/v2.2.0
