### ISSUE TITLE
support for mac-m1 cpu

### ISSUE THREAD

**Issue by MorphisHe** [TimothyYe/ydict#25]
Hi, thanks for the wonderful repo. Any plans on making this work for mac-m1 cpu?

**Comment by MorphisHe** [comment]
nvm please ignore this issue.

**Comment by TimothyYe** [comment]
m1 is based on the ARM platform, you can try this release: https://github.com/TimothyYe/ydict/releases/download/V2.1/ydict-arm64-2.1.tar.gz
