### ISSUE TITLE
汉字输出错误

### ISSUE THREAD

**Issue by YiHui-Liu** [TimothyYe/ydict#27]
为帮助我们快速定位issue，请描述如下几点:
- 操作场景
Windows10 + Powershell，使用`ydict -p 30`
- 程序异常或者错误信息
汉字输出错误
![image](https://user-images.githubusercontent.com/30190271/116419575-c5e6b700-a86f-11eb-82f5-2b1522e9d47c.png)
![image](https://user-images.githubusercontent.com/30190271/116419581-c7b07a80-a86f-11eb-9fc6-186c4a123944.png)

**Comment by TimothyYe** [comment]
这有可能是编码问题，MacOS下显示正常

**Comment by YiHui-Liu** [comment]
> 这有可能是编码问题，MacOS下显示正常

更改单词本的编码吗？这或许需要修改源代码的写出设置？
