### ISSUE TITLE
请问为什么使用了 proxy？

### ISSUE THREAD

**Issue by pathbox** [TimothyYe/ydict#3]
你好，我阅读了ydict 的源码，并且在电脑上安装使用了dict， 挺好用的。
请问 为什么 在query 中使用了proxy的方式？ 直接对 youdao的接口进行调用也可以不是吗？

我在Ubuntu 14.04 上 没有声音播放

**Comment by TimothyYe** [comment]
@pathbox 你好，程序支持SOCKS5的proxy，是提供给没有网络直连环境的同学可以通过proxy的方式配置和访问网络。proxy启用是有条件判断的，必须配置了.env文件，并且在文件中指定了proxy，接口的调用才会通过proxy，否则是会直接进行调用的。

关于声音的问题，Ubuntu 14.04是否配置了声卡？是否有安装mpg123？可以在Ubuntu中先用mpg123播放mp3文件看有没有声音。

**Comment by pathbox** [comment]
Hi, 
   明白了。 我把源码完整看完了，你是把 整个网页请求过来，然后 用goquery 进行抓取网页显示数据，再终端显示。把 mp3 音频文件下载到 临时文件目录，然后 调用mpg123 播放音频文件 发音。不知道说的对不对。 我昨天试了 应该装了mpg123，电脑在公司，上班的时候 去试一下是否可以播放mp3文件，发音这个还是挺有意思的，不过 应该只能在UNIX系统下，也许可以优化 考虑mac系统也做到发音，是不是mac系统有权限限制？

**Comment by TimothyYe** [comment]
@pathbox 是的，流程就是这样。
我开发机器就是mac，是可以发音的，也是装mpg123。

**Comment by pathbox** [comment]
是的，可以。我在mac上可以发音
