### ISSUE TITLE
是否想过把 更多例句，更多翻译 也给获取到

### ISSUE THREAD

**Issue by pathbox** [TimothyYe/ydict#4]
一个小建议： 是否想过把 更多例句，更多翻译 也给获取到。当然，简单的翻译一般情况都够用了。

**Comment by TimothyYe** [comment]
这样估计信息量有点大…… 哈哈……

**Comment by pathbox** [comment]
@TimothyYe 哈哈。 应该需要模拟鼠标点击 `更多翻译句` 的链接的动作，然后再获得请求到的html content，有道应该是用的ajax一类的请求，在用goquery去获取抓取这个html content
我没试过这种爬虫动作，只是看过文章介绍说是可以实现，但是是用的Python 的爬虫库

**Comment by pathbox** [comment]
这两天玩了下Python 的爬虫， selenuim + phantomjs 可以模拟浏览器并且做各种JavaScript的操作，可以实现这个功能。 然后我就搜到了这个 https://github.com/sourcegraph/go-selenium 
我想我可以找个时间把这个尝试实现一下

**Comment by TimothyYe** [comment]
V1.0版本已实现
