### ISSUE TITLE
zsh: command not found: ydict

### ISSUE THREAD

**Issue by lrvy** [TimothyYe/ydict#8]
After run command "go get github.com/TimothyYe/ydict",  and try to run ydict test, i found ydict command not found.
ydict was installted in "/Users/`$(whoami)`/Projects/Golang/src/github.com/TimothyYe/ydict"

this is go env:
GOARCH="amd64"
GOBIN="/usr/local/opt/go/libexec/bin"
GOCACHE="/Users/`$(whoami)`/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/`$(whoami)`/Projects/Golang"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11.1/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/vj/kq1kd1p56l3fcbnsl_77hvnc0000gn/T/go-build769805951=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by TimothyYe** [comment]
Try to check `/usr/local/opt/go/libexec/bin`, ydict may be installed to this place.

**Comment by TimothyYe** [comment]
You may need to add `/usr/local/opt/go/libexec/bin` to your system `PATH`.

**Comment by lrvy** [comment]
> You may need to add `/usr/local/opt/go/libexec/bin` to your system `PATH`.

Fixed it, thx 😊.
